@startuml

title __REGION's Class Diagram__\n

  namespace org.optaweb.vehiclerouting {
    namespace service.region {
      class org.optaweb.vehiclerouting.service.region.BoundingBox {
          + BoundingBox()
          + getNorthEast()
          + getSouthWest()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.region {
      interface org.optaweb.vehiclerouting.service.region.Region {
          {abstract} + getBounds()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.region {
      class org.optaweb.vehiclerouting.service.region.RegionProperties {
          - countryCodes : List<String>
          + getCountryCodes()
          + setCountryCodes()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.region {
      class org.optaweb.vehiclerouting.service.region.RegionService {
          + boundingBox()
          + countryCodes()
          ~ RegionService()
      }
    }
  }
  

  org.optaweb.vehiclerouting.service.region.BoundingBox o-- org.optaweb.vehiclerouting.domain.Coordinates : northEast
  org.optaweb.vehiclerouting.service.region.BoundingBox o-- org.optaweb.vehiclerouting.domain.Coordinates : southWest
  org.optaweb.vehiclerouting.service.region.RegionService o-- org.optaweb.vehiclerouting.service.region.Region : region
  org.optaweb.vehiclerouting.service.region.RegionService o-- org.optaweb.vehiclerouting.service.region.RegionProperties : regionProperties


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
