@startuml

title __DISTANCE's Class Diagram__\n

  namespace org.optaweb.vehiclerouting {
    namespace service.distance {
      class org.optaweb.vehiclerouting.service.distance.DistanceCalculationException {
          + DistanceCalculationException()
          + DistanceCalculationException()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.distance {
      interface org.optaweb.vehiclerouting.service.distance.DistanceCalculator {
          {abstract} + travelTimeMillis()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.distance {
      class org.optaweb.vehiclerouting.service.distance.DistanceMatrixImpl {
          - matrix : Map<Location, Map<Long, Distance>>
          + addLocation()
          + clear()
          + dimension()
          + distance()
          + put()
          + removeLocation()
          ~ DistanceMatrixImpl()
          - calculateDistance()
          - updateMatrixLazily()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.distance {
      interface org.optaweb.vehiclerouting.service.distance.DistanceRepository {
          {abstract} + deleteAll()
          {abstract} + deleteDistances()
          {abstract} + getDistance()
          {abstract} + saveDistance()
      }
    }
  }
  

  org.optaweb.vehiclerouting.service.distance.DistanceMatrixImpl .up.|> org.optaweb.vehiclerouting.service.location.DistanceMatrix
  org.optaweb.vehiclerouting.service.distance.DistanceMatrixImpl o-- org.optaweb.vehiclerouting.service.distance.DistanceCalculator : distanceCalculator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
