@startuml

title __ROUTING's Class Diagram__\n

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      class org.optaweb.vehiclerouting.plugin.routing.AirDistanceRouter {
          {static} # KILOMETERS_PER_DEGREE : double
          {static} # MILLIS_IN_ONE_HOUR : long
          {static} # TRAVEL_SPEED_KPH : int
          + getBounds()
          + getPath()
          + travelTimeMillis()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      class org.optaweb.vehiclerouting.plugin.routing.GraphHopperRouter {
          - graphHopper : GraphHopperOSM
          + getBounds()
          + getPath()
          + travelTimeMillis()
          ~ GraphHopperRouter()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      class org.optaweb.vehiclerouting.plugin.routing.RoutingConfig {
          - graphDir : Path
          - graphHopperDir : Path
          {static} - logger : Logger
          - osmDir : Path
          - osmDownloadUrl : Optional<String>
          - osmFile : Path
          ~ RoutingConfig()
          {static} ~ downloadOsmFile()
          ~ graphHopper()
          - initDirs()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      class org.optaweb.vehiclerouting.plugin.routing.RoutingEngineException {
          ~ RoutingEngineException()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      class org.optaweb.vehiclerouting.plugin.routing.RoutingProperties {
          - ghDir : String
          - osmDir : String
          - osmDownloadUrl : Optional<String>
          - osmFile : String
          + getEngine()
          + getGhDir()
          + getOsmDir()
          + getOsmDownloadUrl()
          + getOsmFile()
          + setEngine()
          + setGhDir()
          + setOsmDir()
          + setOsmDownloadUrl()
          + setOsmFile()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace plugin.routing {
      enum RoutingEngine {
        AIR
        GRAPHHOPPER
      }
    }
  }
  

  org.optaweb.vehiclerouting.plugin.routing.AirDistanceRouter .up.|> org.optaweb.vehiclerouting.service.distance.DistanceCalculator
  org.optaweb.vehiclerouting.plugin.routing.AirDistanceRouter .up.|> org.optaweb.vehiclerouting.service.region.Region
  org.optaweb.vehiclerouting.plugin.routing.AirDistanceRouter .up.|> org.optaweb.vehiclerouting.service.route.Router
  org.optaweb.vehiclerouting.plugin.routing.GraphHopperRouter .up.|> org.optaweb.vehiclerouting.service.distance.DistanceCalculator
  org.optaweb.vehiclerouting.plugin.routing.GraphHopperRouter .up.|> org.optaweb.vehiclerouting.service.region.Region
  org.optaweb.vehiclerouting.plugin.routing.GraphHopperRouter .up.|> org.optaweb.vehiclerouting.service.route.Router
  org.optaweb.vehiclerouting.plugin.routing.RoutingProperties o-- org.optaweb.vehiclerouting.plugin.routing.RoutingProperties.RoutingEngine : engine
  org.optaweb.vehiclerouting.plugin.routing.RoutingProperties +-down- org.optaweb.vehiclerouting.plugin.routing.RoutingProperties.RoutingEngine


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
