@startuml

title __ROUTE's Class Diagram__\n

  namespace org.optaweb.vehiclerouting {
    namespace service.route {
      class org.optaweb.vehiclerouting.service.route.RouteChangedEvent {
          - depotId : Long
          - routes : Collection<ShallowRoute>
          - vehicleIds : List<Long>
          - visitIds : List<Long>
          + RouteChangedEvent()
          + depotId()
          + distance()
          + routes()
          + vehicleIds()
          + visitIds()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.route {
      class org.optaweb.vehiclerouting.service.route.RouteListener {
          {static} - logger : Logger
          - routingPlanEvent : Event<RoutingPlan>
          + getBestRoutingPlan()
          + onApplicationEvent()
          ~ RouteListener()
          - findLocationById()
          - findVehicleById()
          - track()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.route {
      interface org.optaweb.vehiclerouting.service.route.Router {
          {abstract} + getPath()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.route {
      interface org.optaweb.vehiclerouting.service.route.RoutingPlanConsumer {
          {abstract} + consumePlan()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.route {
      class org.optaweb.vehiclerouting.service.route.ShallowRoute {
          + depotId : long
          + vehicleId : long
          + visitIds : List<Long>
          + ShallowRoute()
          + toString()
      }
    }
  }
  

  org.optaweb.vehiclerouting.service.route.RouteChangedEvent o-- org.optaweb.vehiclerouting.domain.Distance : distance
  org.optaweb.vehiclerouting.service.route.RouteListener o-- org.optaweb.vehiclerouting.domain.RoutingPlan : bestRoutingPlan
  org.optaweb.vehiclerouting.service.route.RouteListener o-- org.optaweb.vehiclerouting.service.location.LocationRepository : locationRepository
  org.optaweb.vehiclerouting.service.route.RouteListener o-- org.optaweb.vehiclerouting.service.route.Router : router
  org.optaweb.vehiclerouting.service.route.RouteListener o-- org.optaweb.vehiclerouting.service.vehicle.VehicleRepository : vehicleRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
