@startuml

title __DEMO's Class Diagram__\n

  namespace org.optaweb.vehiclerouting {
    namespace service.demo {
      class org.optaweb.vehiclerouting.service.demo.DemoProperties {
          - dataSetDir : Optional<String>
          + getDataSetDir()
          + setDataSetDir()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.demo {
      class org.optaweb.vehiclerouting.service.demo.DemoService {
          {static} ~ MAX_TRIES : int
          + DemoService()
          + demos()
          + exportDataSet()
          + loadDemo()
          - addWithRetry()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.demo {
      class org.optaweb.vehiclerouting.service.demo.RoutingProblemConfig {
          {static} - logger : Logger
          ~ RoutingProblemConfig()
          ~ routingProblems()
          {static} - belgiumReader()
          {static} - isReadableDir()
          - localDataSets()
      }
    }
  }
  

  namespace org.optaweb.vehiclerouting {
    namespace service.demo {
      class org.optaweb.vehiclerouting.service.demo.RoutingProblemList {
          - routingProblems : Map<String, RoutingProblem>
          ~ RoutingProblemList()
          ~ all()
          ~ byName()
      }
    }
  }
  

  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.demo.dataset.DataSetMarshaller : dataSetMarshaller
  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.location.LocationRepository : locationRepository
  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.location.LocationService : locationService
  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.demo.RoutingProblemList : routingProblems
  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.vehicle.VehicleRepository : vehicleRepository
  org.optaweb.vehiclerouting.service.demo.DemoService o-- org.optaweb.vehiclerouting.service.vehicle.VehicleService : vehicleService
  org.optaweb.vehiclerouting.service.demo.RoutingProblemConfig o-- org.optaweb.vehiclerouting.service.demo.dataset.DataSetMarshaller : dataSetMarshaller
  org.optaweb.vehiclerouting.service.demo.RoutingProblemConfig o-- org.optaweb.vehiclerouting.service.demo.DemoProperties : demoProperties


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
